name: Node.js Package

on:
  push:
    branches:
      - master
  #release:
  #  types: [created]

jobs:
  #build:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: actions/setup-node@v2
  #      with:
  #        node-version: 16
  #    - run: yarn

  publish-gpr:
    #needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@uptownhr'
      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'uptownhr@gmail.com'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_PAT@github.com/uptownhr/lerna-example
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_GH}}
      #- run: npm whoami
      #  env:
      #    NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: yarn revision
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_GH}}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
