name: Node.js Package

on:
  push:
    branches:
      - master
  #release:
  #  types: [created]

jobs:
  #build:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: actions/setup-node@v2
  #      with:
  #        node-version: 16
  #    - run: yarn

  publish-gpr:
    #needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@uptownhr'
      - run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_GH}}
      #- run: npm whoami
      #  env:
      #    NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_GH}}
