name: Node.js Package

on:
  push:
    branches:
      - master
  #release:
  #  types: [created]

jobs:
  #build:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: actions/setup-node@v2
  #      with:
  #        node-version: 16
  #    - run: yarn

  publish-gpr:
    #needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_GH}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@uptownhr'
      - name: Git Identity
        run: |
          git config --global user.name "@$GITHUB_ACTOR"
          git config --global user.email 'uptownhr@gmail.com'
      - run: yarn
      - run: yarn release
